import { createClient } from "next-sanity";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, "../.env.local");

// Simple loader for .env.local
if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#") && trimmed.includes("=")) {
      const idx = trimmed.indexOf("=");
      const key = trimmed.slice(0, idx).trim();
      const val = trimmed.slice(idx + 1).trim();
      if (!process.env[key]) {
        process.env[key] = val;
      }
    }
  }
}

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "n5zz3lqj";
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || "2026-09-18";
const token = process.env.SANITY_API_TOKEN;

console.log("==================================================");
console.log("🛠️  Sanity Backend & CRUD Verification Script");
console.log("==================================================");
console.log(`• Project ID: ${projectId}`);
console.log(`• Dataset:    ${dataset}`);
console.log(`• API Version:${apiVersion}`);
console.log(`• Write Token:${token ? " [CONFIGURED: " + token.slice(0, 6) + "...]" : " [NOT SET in .env.local]"}`);
console.log("==================================================\n");

// 1. Read Client
const readClient = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: false, // Bypass CDN for immediate test results
});

// 2. Write Client
const writeClient = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: false,
  token,
});

async function runTests() {
  // --------------------------------------------------------------------------
  // TEST 1: READ (Querying Sanity Content Lake)
  // --------------------------------------------------------------------------
  console.log("▶ [1/4] Testing READ (Fetching resources from Sanity Content Lake)...");
  try {
    const existing = await readClient.fetch(
      `*[_type == "resource"] | order(publishedAt desc) { _id, title, category, tags, author, publishedAt }`
    );
    console.log(`  ✔ Successfully connected to Sanity!`);
    console.log(`  ✔ Total resources currently in dataset: ${existing.length}`);
    if (existing.length > 0) {
      console.log(`  ✔ Sample document:`, existing[0]);
    }
  } catch (err) {
    console.error(`  ✖ READ failed:`, err.message);
    return;
  }

  // --------------------------------------------------------------------------
  // TEST 2, 3, 4: WRITE (CREATE, UPDATE, DELETE)
  // --------------------------------------------------------------------------
  if (!token) {
    console.log("\n⚠️  SANITY_API_TOKEN is not set in web/.env.local");
    console.log("   To test CREATE, UPDATE, and DELETE operations programmatically:");
    console.log("   1. Go to https://www.sanity.io/manage");
    console.log("   2. Select project '31113 RoboLads' -> API -> Tokens");
    console.log("   3. Click 'Add API token', give it 'Editor' permissions, and copy the token.");
    console.log("   4. Paste it into web/.env.local: SANITY_API_TOKEN=sk...");
    console.log("   5. Re-run this script: npm run test:crud\n");
    console.log("👉 Alternatively, you can test full CRUD visually in Sanity Studio:");
    console.log("   Run: cd studio && pnpm dev (opens http://localhost:3333)\n");
    return;
  }

  console.log("\n▶ [2/4] Testing CREATE (Creating a test resource document)...");
  let createdId = null;
  try {
    const newDoc = await writeClient.create({
      _type: "resource",
      title: "Test Resource (Auto-generated by test script)",
      category: "CAD",
      tags: ["test", "cad", "automated"],
      author: "CRUD Verification",
      publishedAt: new Date().toISOString(),
    });
    createdId = newDoc._id;
    console.log(`  ✔ Document created successfully! ID: ${createdId}`);
  } catch (err) {
    console.error(`  ✖ CREATE failed:`, err.message);
    return;
  }

  console.log("\n▶ [3/4] Testing UPDATE (Patching title of document)...");
  try {
    const updatedDoc = await writeClient
      .patch(createdId)
      .set({ title: "Test Resource (Updated Title)" })
      .commit();
    console.log(`  ✔ Document patched successfully! New title: "${updatedDoc.title}"`);
  } catch (err) {
    console.error(`  ✖ UPDATE failed:`, err.message);
  }

  console.log("\n▶ [4/4] Testing DELETE (Cleaning up test document)...");
  try {
    await writeClient.delete(createdId);
    console.log(`  ✔ Document deleted successfully! ID: ${createdId}`);
  } catch (err) {
    console.error(`  ✖ DELETE failed:`, err.message);
  }

  console.log("\n==================================================");
  console.log("🎉 ALL CRUD TESTS COMPLETED SUCCESSFULLY!");
  console.log("==================================================");
}

runTests();
